# Numpy Notları

* Numpy Python'ın bir kütüphanesidir. İçerisinde farklı metotlar kulllanılır. İstatistiksel işlemler yapmak için kullanılır.

In [1173]:
import numpy as np 
#numpy kütüphanesi import edilir ve np takma adı kullanılır.

In [1174]:
arr = np.array([3,5,7]) #array metodu oluşturdum. 1*3lük vektör oluşturuldu.
print(arr)

[3 5 7]


In [1175]:
arry=np.array([1,2,54,14,36,74])
print(arry.shape) #arrayin shape'ine bakılır. 5*1'lik bir matris.

(6,)


In [1176]:
i = arry.reshape(2,3)
print(i) #vektör 8 satır ve 9 sütunluk matrise dönüştü.

[[ 1  2 54]
 [14 36 74]]


In [1177]:
print("shape: ",i.shape) #(2,3)
print("dimension: ",i.ndim) #oluşturulan matrisin boyutuna bakılır,boyut kontrolü yapar. dimension:2

print("data type: ",i.dtype.name) #data type: int32 type'ları görmek için kullanılır.

print("size: ",i.size) #size: 6 reshape'ten önceki boyutu gösterir.

print("type: ",type(i)) #type:  <class 'numpy.ndarray'>

shape:  (2, 3)
dimension:  2
data type:  int32
size:  6
type:  <class 'numpy.ndarray'>


In [1178]:
array3= np.array([[18,12,19],["a","b","c"],[6,1,4]]) #reshape yapmadan da boyutu değiştirilebilir. 3 boyutlu dizi oluşturdum.
print(array3)

[['18' '12' '19']
 ['a' 'b' 'c']
 ['6' '1' '4']]


In [1179]:
print(array3.shape) #(3,3) boyutlara sahiptir.

(3, 3)


In [1180]:
print(array3[0]) #dizinin 1. elemanlarını yazdırır.
print(array3[0,1]) #dizinin 1.satırı ve 2. sütununa erişir.

['18' '12' '19']
12


In [1181]:
zeros= np.zeros((3,3)) #3*3lük sıfırlardan oluşan matris oluşturulur.

zeros[0,0]=8
print(zeros)

[[8. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [1182]:
np.ones((5,6)) #5*6lık 1'lerden oluşan matris oluşur.

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [1183]:
np.empty((5,5)) #boş ve random değerlere sahip array oluşur.

array([[1.89146896e-307, 1.37961302e-306, 6.23053614e-307,
        6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 9.34598925e-307,
        1.42418715e-306, 1.95819401e-306],
       [1.37961370e-306, 6.23054633e-307, 9.34598926e-307,
        6.89804132e-307, 9.34598926e-307],
       [8.01091099e-307, 1.24610927e-306, 2.22522597e-306,
        8.90109671e-307, 1.37962388e-306],
       [9.34598925e-307, 6.89807867e-307, 1.11261570e-306,
        8.34451504e-308, 1.19333452e-152]])

In [1184]:
dizi= np.array([5,4,8,9,6,3])
print(dizi[0:5]) #0'dan 5'e kadar sayıları yazdırır.
print(dizi[:5])
print(dizi[5:]) #5. indisin en sonuna kadar yazdırır.
print(dizi[-1:-5])
print(dizi[::3])

[5 4 8 9 6]
[5 4 8 9 6]
[3]
[]
[5 9]


In [1185]:
dizi1= np.array([2.5,5.7,7.6])
irem=dizi1.astype('i')
print(irem) #tam kısmı alır sadece
print(irem.dtype) #typeını gösterir.

[2 5 7]
int32


In [1186]:
dizi1= np.array([5,4,6,8,4,2])
a= dizi1.copy()
dizi1[5]=53 #5. index yerine 53 değeri getirildi. orjinal dizi değiştirilmiş oldu.
print(dizi1)
print(a)

[ 5  4  6  8  4 53]
[5 4 6 8 4 2]


In [1187]:
b= dizi1.view() #orjinal dizi de değişmiş oldu. 
dizi1[4]=50
print(dizi1)
print(b)
print(b.base)

[ 5  4  6  8 50 53]
[ 5  4  6  8 50 53]
[ 5  4  6  8 50 53]


In [1188]:
irem= np.array([4,5,9,8])
for i in irem:
    print(i) #dizinin ögelerini yazdırır.

4
5
9
8


In [1189]:
iremm=np.array([[2,5,6],[7,8,4]])
for i in iremm:
    print(i) #2 boyutlu dizinin ögelerini yazdırır.

for i in iremm:
    for r in i:
        print(r) #dizinin tüm ögelerini alt alta sıralar.

[2 5 6]
[7 8 4]
2
5
6
7
8
4


In [1190]:
for a in np.nditer(iremm):
    print(a) #herbirini alt alta sıralar

2
5
6
7
8
4


In [1191]:
ir1= np.array([1,4,5])
ir2= np.array([5,8,7])
arry = np.concatenate((ir1,ir2))
print(arry) #iki diziyi birleştirir. 

arry = np.stack((ir1,ir2), axis=1)
print(arry)

arry = np.vstack((ir1, ir2)) #sütunlar boyunca istifler
print(arry)

[1 4 5 5 8 7]
[[1 5]
 [4 8]
 [5 7]]
[[1 4 5]
 [5 8 7]]


In [1192]:
arr = np.array([1, 2, 3, 4, 5, 6])
irm = np.array_split(arr, 2) #diziyi 2 parçaya böler.
print(irm)

[array([1, 2, 3]), array([4, 5, 6])]


In [1193]:
a= np.where(arr == 5)
print(a) #değerin 5 olduğu indexi buldu. 

a= np.where(arr%2==0)
print(a) #değerlerin çift olduğu indexleri bulur.

a = np.searchsorted(arr, 5, side='right')
print(a)

(array([4], dtype=int64),)
(array([1, 3, 5], dtype=int64),)
5


In [1194]:
print(np.sort(arr)) #diziyi sıralar

[1 2 3 4 5 6]


In [1195]:
x= np.array([4,5,2])
y=np.array([1,5,8])
print(x+y) #basit matematiksel işlemlerde boyutların aynı olması gerekir.
print(x-y)
print(x**y)

[ 5 10 10]
[ 3  0 -6]
[   4 3125  256]


In [1196]:
aa= np.array([[1,2,3],[4,8,5],[7,8,9]])
array_transpose = aa.T #arrayın transpose'u alınır.

print(array_transpose)

[[1 4 7]
 [2 8 8]
 [3 5 9]]
